# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YouNeedADoorbell' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YouNeedADoorbell
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Database', '~> 4.0'
  pod 'PhoneNumberKit', '~> 2.1'
  pod 'SwiftDate', '~> 4.0'
  pod 'SwiftyJSON'

end
